name: GitHub Page Publisher
run-name: ${{ github.actor }} is publish github page  🚀
on: [merge]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: npm run deploy
      - run: echo "🍏 This job's status is ${{ job.status }}."