name: GitHub Page Publisher
run-name: ${{ github.actor }} is publish github page  🚀
on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install dependencies
        run: npm install
      - name: Build project And Deploy
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run deploy
      - run: echo "🍏 This job's status is ${{ job.status }}."